import { PREFIX_CONST_REQUEST, PREFIX_NAME } from './base';

export const ON_CHANGE_OPEN_KEYS = `${PREFIX_NAME}_ON_CHANGE_OPEN_KEYS`;

export const APP = {
  ...PREFIX_CONST_REQUEST('ROUTER'),
};

export const LOGIN = {
  ...PREFIX_CONST_REQUEST('LOGOUT'),
  ...PREFIX_CONST_REQUEST('REFRESH'),
  ...PREFIX_CONST_REQUEST('SUBMITING'),
};

export const ADMINPOST = {
  ...PREFIX_CONST_REQUEST('SEARCH'),
  ...PREFIX_CONST_REQUEST('CREATE'),
  ...PREFIX_CONST_REQUEST('UPDATE'),
  ...PREFIX_CONST_REQUEST('DELETE'),
};

